// Generated by CoffeeScript 1.12.4
(function() {
  var _deps;

  _deps = ['/shtml/vendor/riot/riot-hot-reload.js', '/shtml/dev/riot-livereload-plugins.coffee.js'];

  loadjs(_deps, {
    success: function() {
      console.log("Run livereloadx --include '*.tag.js' in your static folder");
      return loadjs(['http://127.0.0.1:35729/livereload.js']);
    }
  });

}).call(this);
